# Generated by Django 4.2.7 on 2024-01-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_usermodel_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
