# Generated by Django 4.2.7 on 2024-01-15 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_usermodel_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="User registration date",
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="last_login",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="User last login date",
                null=True,
                verbose_name="last login",
            ),
        ),
    ]
