# Generated by Django 4.2.7 on 2024-01-25 09:44

from django.db import migrations, models
import users.models.user_model


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_usermodel_date_joined_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="photo",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="User profile image",
                null=True,
                upload_to=users.models.user_model.rename,
                verbose_name="image",
            ),
        ),
    ]
