# Generated by Django 5.0.1 on 2024-02-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_usermodel_photo_usermodel_image"),
        ("workshops", "0031_alter_reviewresponsemodel_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="favorite_workshops",
            field=models.ManyToManyField(
                blank=True,
                help_text="User favorite workshops",
                related_name="favorite_users",
                to="workshops.workshopmodel",
                verbose_name="favorite workshops",
            ),
        ),
    ]
