# Generated by Django 5.0.1 on 2024-02-22 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("questions", "0016_rename_questionmodel_question_and_more"),
        ("security", "0010_rename_verificationcodemodel_verificationcode_and_more"),
        ("services", "0015_rename_servicemodel_service_and_more"),
        ("users", "0006_usermodel_favorite_workshops"),
        ("vehicles", "0017_alter_vehiclemodel_vin"),
        ("workshops", "0040_workshopmodel_banner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserModel",
            new_name="User",
        ),
    ]
