# Generated by Django 5.0.1 on 2024-03-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_deleted_at_user_restored_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time of last update.",
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="User registration date",
                verbose_name="date joined",
            ),
        ),
    ]
