# Generated by Django 4.2.7 on 2024-01-23 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workshops", "0006_remove_questionresponsemodel_client_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Question id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        help_text="Question asked by the client",
                        max_length=50,
                        verbose_name="question",
                    ),
                ),
                (
                    "questioned_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Questioned at",
                        verbose_name="questioned at",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client who asked the question",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        help_text="Workshop who the question was asked",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="workshops.workshopmodel",
                        verbose_name="workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "db_table": "question",
            },
        ),
        migrations.CreateModel(
            name="QuestionResponseModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Question id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        help_text="Questioned at",
                        max_length=255,
                        verbose_name="response",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Responded at",
                        verbose_name="responded at",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Client who asked the question",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question asked",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="questions.questionmodel",
                        verbose_name="question",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Workshop who the question was asked",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_responses",
                        to="workshops.workshopmodel",
                        verbose_name="workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "question response",
                "verbose_name_plural": "question responses",
                "db_table": "question_response",
            },
        ),
    ]
