# Generated by Django 5.0.1 on 2024-01-31 03:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionmodel",
            old_name="questioned_at",
            new_name="created_at",
        ),
    ]
