# Generated by Django 5.0.1 on 2024-01-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_rename_questioned_at_questionmodel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Created at", verbose_name="created at"
            ),
        ),
    ]
