# Generated by Django 5.0.1 on 2024-01-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_alter_questionmodel_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionmodel",
            old_name="question",
            new_name="message",
        ),
        migrations.AddField(
            model_name="questionmodel",
            name="number",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="Question number",
                null=True,
                verbose_name="number",
            ),
        ),
    ]
