# Generated by Django 5.0.1 on 2024-01-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0004_rename_question_questionmodel_message_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionmodel",
            old_name="message",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="questionresponsemodel",
            old_name="response",
            new_name="body",
        ),
        migrations.AlterField(
            model_name="questionmodel",
            name="id",
            field=models.AutoField(
                editable=False,
                help_text="The unique identifier of the question.",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
    ]
