# Generated by Django 5.0.1 on 2024-01-31 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0006_rename_responded_at_questionresponsemodel_created_at"),
        ("workshops", "0025_alter_reviewresponsemodel_response"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionresponsemodel",
            name="workshop",
        ),
        migrations.AlterField(
            model_name="questionmodel",
            name="body",
            field=models.CharField(
                help_text="Question asked by the client",
                max_length=200,
                verbose_name="question",
            ),
        ),
        migrations.AlterField(
            model_name="questionmodel",
            name="client",
            field=models.ForeignKey(
                editable=False,
                help_text="Client who asked the question",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="client",
            ),
        ),
        migrations.AlterField(
            model_name="questionmodel",
            name="workshop",
            field=models.ForeignKey(
                editable=False,
                help_text="Workshop who the question was asked",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="workshops.workshopmodel",
                verbose_name="workshop",
            ),
        ),
        migrations.AlterField(
            model_name="questionresponsemodel",
            name="body",
            field=models.TextField(
                help_text="Questioned at", max_length=1000, verbose_name="response"
            ),
        ),
        migrations.AlterField(
            model_name="questionresponsemodel",
            name="client",
            field=models.ForeignKey(
                editable=False,
                help_text="Client who answered the question.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="question_responses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="client",
            ),
        ),
        migrations.AlterField(
            model_name="questionresponsemodel",
            name="question",
            field=models.OneToOneField(
                editable=False,
                help_text="Question asked",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="response",
                to="questions.questionmodel",
                verbose_name="question",
            ),
        ),
    ]
