# Generated by Django 5.0.1 on 2024-01-31 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0007_remove_questionresponsemodel_workshop_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionresponsemodel",
            old_name="client",
            new_name="user",
        ),
    ]
