# Generated by Django 5.0.1 on 2024-01-31 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0008_rename_client_questionresponsemodel_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionmodel",
            old_name="client",
            new_name="user",
        ),
    ]
