# Generated by Django 5.0.1 on 2024-02-01 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0010_remove_questionresponsemodel_question_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionresponsemodel",
            old_name="questions",
            new_name="question",
        ),
    ]
