# Generated by Django 5.0.1 on 2024-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0011_rename_questions_questionresponsemodel_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionmodel",
            name="number",
            field=models.PositiveIntegerField(
                editable=False, help_text="Question number", verbose_name="number"
            ),
        ),
    ]
