# Generated by Django 5.0.1 on 2024-02-02 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0012_alter_questionmodel_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionmodel",
            name="votes",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Number of votes",
                verbose_name="votes",
            ),
        ),
        migrations.AlterField(
            model_name="questionresponsemodel",
            name="question",
            field=models.ForeignKey(
                editable=False,
                help_text="Question asked",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="answers",
                to="questions.questionmodel",
                verbose_name="question",
            ),
        ),
    ]
