# Generated by Django 5.0.1 on 2024-02-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0014_questionresponsemodel_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionmodel",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Indicates if the question is deleted",
                verbose_name="is deleted",
            ),
        ),
        migrations.AddField(
            model_name="questionmodel",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Updated at", verbose_name="updated at"
            ),
        ),
        migrations.AddField(
            model_name="questionresponsemodel",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Indicates if the question response is deleted",
                verbose_name="is deleted",
            ),
        ),
        migrations.AddField(
            model_name="questionresponsemodel",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Updated at", verbose_name="updated at"
            ),
        ),
    ]
