# Generated by Django 5.0.1 on 2024-02-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0017_question_deleted_at_question_restored_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="questionresponse",
            name="is_deleted",
        ),
    ]
