trigger:
  tags:
    include:
      - 'v*'

resources:
  - repo: self

pool:
  name: 'Default'

variables:
  dockerHubConnection: 'dockerHubConnection'
  dockerHubUserName: 'vxgamex'
  dockerImageName: 'automatico-api'
  dockerFilePath: 'Dockerfile'

stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: BuildAndPush
        displayName: 'Build and Push'
        steps:
          - task: Docker@2
            displayName: 'Build and Push Docker Image'
            inputs:
              containerRegistry: '$(dockerHubConnection)'
              repository: '$(dockerHubUserName)/$(dockerImageName)'
              command: 'buildAndPush'
              Dockerfile: '$(dockerFilePath)'
              tags: |
                $(Build.BuildId)
                latest
