trigger:
  tags:
    include:
      - 'v*'

resources:
  - repo: self

pool:
  vmImage: 'windows-latest'

variables:
  dockerHubConnection: 'dockerHubConnection' # Nombre de la conexión de servicio a Docker Hub en Azure DevOps
  dockerHubUserName: 'vxgamex'              # Nombre de usuario de Docker Hub
  dockerImageName: 'automatico-api'         # Nombre de la imagen de Docker
  dockerFilePath: 'Dockerfile'              # Ruta al Dockerfile en tu repositorio

stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: BuildAndPush
        displayName: 'Build and Push'
        steps:
          - task: Docker@2
            displayName: 'Build and Push Docker Image'
            inputs:
              containerRegistry: '$(dockerHubConnection)'
              repository: '$(dockerHubUserName)/$(dockerImageName)'
              command: 'buildAndPush'
              Dockerfile: '$(dockerFilePath)'
              tags: |
                $(Build.BuildId)
                latest
