version: '3.8'

services:
  automatico-db:
    container_name: PostgreSQL
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - db.env

  automatico-api:
    container_name: Web-API
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/automatico-api/app/static
      - media_volume:/home/automatico-api/app/media
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - automatico-db
    env_file:
      - app/.env

  nginx:
    container_name: Nginx
    image: nginx:latest
    volumes:
      - static_volume:/home/automatico-api/app/static
      - media_volume:/home/automatico-api/app/media
      - ./nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - automatico-api

volumes:
  postgres-data:
  static_volume:
  media_volume:
