from .change_password_view import ChangePasswordView
from .user_photo_view import UserPhotoView
from .user_profile_view import UserProfileView
from .user_service_view import UserServiceView
from .user_vehicle_view import UserVehicleView
from .user_workshop_service_view import UserWorkshopServiceView
from .user_workshop_view import UserWorkshopView
