# Generated by Django 4.2.7 on 2024-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0002_alter_vehiclemodel_owner"),
        ("workshops", "0002_alter_workshopcontactmodel_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopmodel",
            name="brands",
            field=models.ManyToManyField(
                blank=True,
                help_text="Workshop brands",
                related_name="workshop_brands",
                to="vehicles.vehiclebrandmodel",
                verbose_name="brands",
            ),
        ),
    ]
