# Generated by Django 4.2.7 on 2024-01-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0004_alter_workshopmodel_employees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewmodel",
            name="qualification",
        ),
        migrations.AddField(
            model_name="reviewmodel",
            name="score",
            field=models.DecimalField(
                decimal_places=1,
                default=4.5,
                help_text="Score",
                max_digits=2,
                verbose_name="score",
            ),
        ),
        migrations.AlterField(
            model_name="reviewmodel",
            name="review",
            field=models.TextField(
                help_text="Review message", max_length=255, verbose_name="review"
            ),
        ),
    ]
