# Generated by Django 4.2.7 on 2024-01-24 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workshops.models.workshop


class Migration(migrations.Migration):
    dependencies = [
        (
            "vehicles",
            "0004_alter_vehiclemodel_nickname_alter_vehiclemodel_plate_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workshops", "0006_remove_questionresponsemodel_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopmodel",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the workshop is active or not.",
                verbose_name="is active",
            ),
        ),
        migrations.AlterField(
            model_name="workshopmodel",
            name="brands",
            field=models.ManyToManyField(
                blank=True,
                help_text="The brands of vehicles the workshop works with",
                related_name="workshop_brands",
                to="vehicles.vehiclebrandmodel",
                verbose_name="brands",
            ),
        ),
        migrations.AlterField(
            model_name="workshopmodel",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                help_text="The workshop employees",
                related_name="workshop_employees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="employees",
            ),
        ),
        migrations.AlterField(
            model_name="workshopmodel",
            name="id",
            field=models.AutoField(
                editable=False,
                help_text="The workshop ID.",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="workshopmodel",
            name="name",
            field=models.CharField(
                help_text="The name of the workshop. This field is not case sensitive.",
                max_length=100,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="workshopmodel",
            name="owner",
            field=models.ForeignKey(
                help_text="The account owner of the workshop.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workshops",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="workshopmodel",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="The workshop photo.",
                null=True,
                upload_to=workshops.models.workshop.rename,
                verbose_name="photo",
            ),
        ),
    ]
