# Generated by Django 4.2.7 on 2024-01-25 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "workshops",
            "0007_workshopmodel_is_active_alter_workshopmodel_brands_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewphotomodel",
            name="review",
        ),
        migrations.RemoveField(
            model_name="reviewresponsemodel",
            name="client",
        ),
        migrations.RemoveField(
            model_name="reviewresponsemodel",
            name="review",
        ),
        migrations.RemoveField(
            model_name="reviewresponsemodel",
            name="workshop",
        ),
        migrations.DeleteModel(
            name="ReviewModel",
        ),
        migrations.DeleteModel(
            name="ReviewPhotoModel",
        ),
        migrations.DeleteModel(
            name="ReviewResponseModel",
        ),
    ]
