# Generated by Django 4.2.7 on 2024-01-25 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0008_remove_reviewphotomodel_review_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workshopmodel",
            old_name="photo",
            new_name="image",
        ),
    ]
