# Generated by Django 5.0.1 on 2024-01-29 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0012_reviewmodel_remove_workshopmodel_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopcontactmodel",
            name="workshop",
            field=models.ForeignKey(
                help_text="Workshop",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts",
                to="workshops.workshopmodel",
                verbose_name="workshop",
            ),
        ),
        migrations.AlterField(
            model_name="workshopmodel",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                help_text="The workshop employees",
                related_name="workplace",
                to=settings.AUTH_USER_MODEL,
                verbose_name="employees",
            ),
        ),
    ]
