# Generated by Django 5.0.1 on 2024-01-30 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0013_alter_workshopcontactmodel_workshop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewmodel",
            name="score",
            field=models.DecimalField(
                decimal_places=1,
                default=4.5,
                help_text="Score",
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="score",
            ),
        ),
    ]
