# Generated by Django 5.0.1 on 2024-01-30 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0014_alter_reviewmodel_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewmodel",
            old_name="reviewed_at",
            new_name="created_at",
        ),
    ]
