# Generated by Django 5.0.1 on 2024-01-30 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0015_rename_reviewed_at_reviewmodel_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviewmodel",
            options={"verbose_name": "message", "verbose_name_plural": "reviews"},
        ),
        migrations.RenameField(
            model_name="reviewmodel",
            old_name="review",
            new_name="message",
        ),
        migrations.AlterModelTable(
            name="reviewmodel",
            table="message",
        ),
    ]
