# Generated by Django 5.0.1 on 2024-01-30 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0017_alter_reviewmodel_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewphotomodel",
            old_name="photo",
            new_name="image",
        ),
    ]
