# Generated by Django 5.0.1 on 2024-01-30 15:48

from django.db import migrations, models

import workshops.models.review_image_model


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0018_rename_photo_reviewphotomodel_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviewphotomodel",
            options={
                "verbose_name": "review image",
                "verbose_name_plural": "review images",
            },
        ),
        migrations.AlterField(
            model_name="reviewphotomodel",
            name="image",
            field=models.ImageField(
                help_text="Image",
                upload_to=workshops.models.review_image_model.rename,
                verbose_name="image",
            ),
        ),
    ]
