# Generated by Django 5.0.1 on 2024-01-30 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0019_alter_reviewphotomodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="reviewphotomodel",
            table="review_image",
        ),
    ]
