# Generated by Django 5.0.1 on 2024-01-30 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0020_alter_reviewphotomodel_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReviewPhotoModel",
            new_name="ReviewImageModel",
        ),
    ]
