# Generated by Django 5.0.1 on 2024-01-30 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0021_rename_reviewphotomodel_reviewimagemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewimagemodel",
            name="review",
            field=models.ForeignKey(
                help_text="Review",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="images",
                to="workshops.reviewmodel",
                verbose_name="review",
            ),
        ),
    ]
