# Generated by Django 5.0.1 on 2024-02-02 20:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0026_alter_reviewmodel_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopmodel",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="The workshop location.",
                null=True,
                srid=4326,
                verbose_name="location",
            ),
        ),
    ]
