# Generated by Django 5.0.1 on 2024-02-04 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0027_workshopmodel_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewresponsemodel",
            old_name="response",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="reviewresponsemodel",
            old_name="responded_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="reviewresponsemodel",
            name="workshop",
        ),
        migrations.AlterField(
            model_name="reviewresponsemodel",
            name="client",
            field=models.ForeignKey(
                help_text="Client who asked the question",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review_responses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="client",
            ),
        ),
    ]
