# Generated by Django 5.0.1 on 2024-02-04 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0030_alter_reviewresponsemodel_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewresponsemodel",
            name="review",
            field=models.OneToOneField(
                editable=False,
                help_text="Review",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="response",
                to="workshops.reviewmodel",
                verbose_name="review",
            ),
        ),
    ]
