# Generated by Django 5.0.1 on 2024-02-06 23:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0031_alter_reviewresponsemodel_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The date and time the workshop was created.",
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
    ]
