# Generated by Django 5.0.1 on 2024-02-08 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0032_workshopmodel_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewmodel",
            old_name="score",
            new_name="rating",
        ),
    ]
