# Generated by Django 5.0.1 on 2024-02-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0036_alter_reviewmodel_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopmodel",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time the workshop was last updated.",
                verbose_name="updated at",
            ),
        ),
    ]
