# Generated by Django 5.0.1 on 2024-02-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0038_reviewmodel_is_deleted_reviewmodel_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopmodel",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="The workshop description.",
                max_length=500,
                null=True,
                verbose_name="description",
            ),
        ),
    ]
