# Generated by Django 5.0.1 on 2024-02-22 17:22

import workshops.models.workshop_model
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0039_workshopmodel_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopmodel",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="The workshop banner.",
                null=True,
                upload_to=workshops.models.workshop_model.rename,
                verbose_name="banner",
            ),
        ),
    ]
