# Generated by Django 5.0.1 on 2024-02-22 23:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0016_rename_questionmodel_question_and_more"),
        ("services", "0015_rename_servicemodel_service_and_more"),
        ("users", "0007_rename_usermodel_user"),
        ("vehicles", "0018_rename_vehiclemodel_vehicle_and_more"),
        ("workshops", "0040_workshopmodel_banner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReviewModel",
            new_name="Review",
        ),
        migrations.RenameModel(
            old_name="ReviewImageModel",
            new_name="ReviewImage",
        ),
        migrations.RenameModel(
            old_name="ReviewResponseModel",
            new_name="ReviewResponse",
        ),
        migrations.RenameModel(
            old_name="SpecialityModel",
            new_name="Speciality",
        ),
        migrations.RenameModel(
            old_name="WorkshopModel",
            new_name="Workshop",
        ),
        migrations.RenameModel(
            old_name="WorkshopContactModel",
            new_name="WorkshopContact",
        ),
    ]
