# Generated by Django 5.0.1 on 2024-02-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0042_review_deleted_at_review_restored_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="is_deleted",
        ),
    ]
