# Generated by Django 5.0.1 on 2024-02-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0043_remove_review_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="description",
            field=models.TextField(
                default="N/A",
                help_text="The workshop description.",
                max_length=500,
                verbose_name="description",
            ),
            preserve_default=False,
        ),
    ]
