# Generated by Django 5.0.1 on 2024-03-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0045_rename_message_review_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(
                help_text="Review body", max_length=255, verbose_name="body"
            ),
        ),
    ]
