# Generated by Django 5.0.1 on 2024-03-05 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0017_alter_service_vehicle_alter_service_workshop_and_more"),
        ("workshops", "0046_alter_review_body"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="client",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Service",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reviews",
                to="services.service",
                verbose_name="service",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="workshop",
            field=models.ForeignKey(
                blank=True,
                help_text="Workshop",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="workshops.workshop",
                verbose_name="workshop",
            ),
        ),
        migrations.AlterField(
            model_name="reviewimage",
            name="review",
            field=models.ForeignKey(
                help_text="Review",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="workshops.review",
                verbose_name="review",
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="owner",
            field=models.ForeignKey(
                help_text="The account owner of the workshop.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workshops",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcontact",
            name="workshop",
            field=models.ForeignKey(
                help_text="Workshop",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="workshops.workshop",
                verbose_name="workshop",
            ),
        ),
    ]
