# Generated by Django 5.0.1 on 2024-03-05 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0047_alter_review_client_alter_review_service_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workshop",
            name="vehicles",
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The date and time of creation.",
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time of last update.",
                verbose_name="updated at",
            ),
        ),
        migrations.AddField(
            model_name="reviewresponse",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time of last update.",
                verbose_name="updated at",
            ),
        ),
        migrations.AddField(
            model_name="speciality",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The date and time of creation.",
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="speciality",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time of last update.",
                verbose_name="updated at",
            ),
        ),
        migrations.AddField(
            model_name="workshopcontact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The date and time of creation.",
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workshopcontact",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time of last update.",
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="reviewresponse",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time of creation.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time of creation.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time of last update.",
                verbose_name="updated at",
            ),
        ),
    ]
