# Generated by Django 5.0.1 on 2024-03-06 08:50

import workshops.models.speciality
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0048_remove_workshop_vehicles_reviewimage_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciality",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image",
                null=True,
                upload_to=workshops.models.speciality.rename,
                verbose_name="image",
            ),
        ),
    ]
