# Generated by Django 5.0.1 on 2024-03-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0049_speciality_image"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="review",
                    name="client",
                ),
                migrations.RemoveField(
                    model_name="review",
                    name="service",
                ),
                migrations.RemoveField(
                    model_name="review",
                    name="workshop",
                ),
                migrations.RemoveField(
                    model_name="reviewresponse",
                    name="review",
                ),
                migrations.DeleteModel(
                    name="ReviewImage",
                ),
                migrations.DeleteModel(
                    name="Review",
                ),
                migrations.DeleteModel(
                    name="ReviewResponse",
                ),
            ],
            database_operations=[],
        )
    ]
