# Generated by Django 5.0.1 on 2024-03-07 16:24

import workshops.models.speciality
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0050_remove_review_client_remove_review_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciality",
            name="image",
            field=models.ImageField(
                help_text="Image",
                null=True,
                upload_to=workshops.models.speciality.rename,
                verbose_name="image",
            ),
        ),
    ]
