# Generated by Django 4.2.7 on 2023-12-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("workshops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicemodel",
            name="workshop",
            field=models.ForeignKey(
                blank=True,
                help_text="Workshop",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="workshops.workshopmodel",
                verbose_name="workshop",
            ),
        ),
        migrations.AddField(
            model_name="servicehistorymodel",
            name="service",
            field=models.ForeignKey(
                help_text="Service",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="histories",
                to="services.servicemodel",
                verbose_name="service",
            ),
        ),
        migrations.AddField(
            model_name="servicehistorymodel",
            name="status",
            field=models.ForeignKey(
                help_text="Status",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="histories",
                to="services.servicestatusmodel",
                verbose_name="status",
            ),
        ),
    ]
