# Generated by Django 4.2.7 on 2024-01-17 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicehistorymodel",
            old_name="responsable",
            new_name="response",
        ),
    ]
