# Generated by Django 4.2.7 on 2024-01-17 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0003_rename_responsable_servicehistorymodel_response"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicehistorymodel",
            name="response",
        ),
        migrations.AddField(
            model_name="servicehistorymodel",
            name="responsable",
            field=models.ForeignKey(
                default=1,
                help_text="Responsable",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_histories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="responsable",
            ),
            preserve_default=False,
        ),
    ]
