# Generated by Django 4.2.7 on 2024-01-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_remove_servicehistorymodel_response_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicehistorymodel",
            name="comment",
            field=models.TextField(
                help_text="Comment", max_length=255, verbose_name="comment"
            ),
        ),
    ]
