# Generated by Django 4.2.7 on 2024-01-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_alter_servicehistorymodel_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicemodel",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="End date",
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AlterField(
            model_name="servicemodel",
            name="request_description",
            field=models.TextField(
                blank=True,
                help_text="Request description",
                max_length=255,
                null=True,
                verbose_name="request description",
            ),
        ),
        migrations.AlterField(
            model_name="servicemodel",
            name="response_description",
            field=models.TextField(
                blank=True,
                help_text="Response description",
                max_length=255,
                null=True,
                verbose_name="response description",
            ),
        ),
    ]
