# Generated by Django 4.2.7 on 2024-01-18 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0006_alter_servicemodel_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicehistorymodel",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment",
                max_length=255,
                null=True,
                verbose_name="comment",
            ),
        ),
        migrations.AlterField(
            model_name="servicehistorymodel",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                help_text="Responsable",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_histories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="responsable",
            ),
        ),
    ]
