# Generated by Django 4.2.7 on 2024-01-18 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0004_alter_workshopmodel_employees"),
        ("services", "0007_alter_servicehistorymodel_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicemodel",
            name="workshop",
            field=models.ForeignKey(
                default=1,
                help_text="Workshop",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="workshops.workshopmodel",
                verbose_name="workshop",
            ),
            preserve_default=False,
        ),
    ]
