# Generated by Django 5.0.1 on 2024-01-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0008_alter_servicemodel_workshop"),
        ("workshops", "0014_alter_reviewmodel_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicemodel",
            old_name="request_description",
            new_name="description",
        ),
        migrations.AddField(
            model_name="servicemodel",
            name="number",
            field=models.IntegerField(
                editable=False,
                help_text="Workshop service number",
                null=True,
                verbose_name="workshop service number",
            ),
        ),
        migrations.AddField(
            model_name="servicemodel",
            name="title",
            field=models.CharField(
                help_text="Service title",
                max_length=100,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.RemoveField(
            model_name="servicemodel",
            name="response_description",
        ),
        migrations.AlterUniqueTogether(
            name="servicemodel",
            unique_together={("workshop", "number")},
        ),
    ]
