# Generated by Django 5.0.1 on 2024-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0012_alter_servicemodel_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicemodel",
            name="closed_at",
            field=models.DateTimeField(
                editable=False, help_text="End date", null=True, verbose_name="end date"
            ),
        ),
        migrations.AlterField(
            model_name="servicemodel",
            name="number",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="Workshop service number",
                verbose_name="workshop service number",
            ),
        ),
        migrations.AlterField(
            model_name="servicemodel",
            name="title",
            field=models.CharField(
                help_text="Service title", max_length=100, verbose_name="title"
            ),
        ),
    ]
