# Generated by Django 5.0.1 on 2024-02-04 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0013_alter_servicemodel_closed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicehistorymodel",
            name="responsable",
            field=models.ForeignKey(
                help_text="Responsable",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_histories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="responsable",
            ),
        ),
    ]
