# Generated by Django 5.0.1 on 2024-02-22 23:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0014_alter_servicehistorymodel_responsable"),
        ("vehicles", "0017_alter_vehiclemodel_vin"),
        ("workshops", "0040_workshopmodel_banner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServiceModel",
            new_name="Service",
        ),
        migrations.RenameModel(
            old_name="ServiceHistoryModel",
            new_name="ServiceHistory",
        ),
        migrations.RenameModel(
            old_name="ServiceStatusModel",
            new_name="ServiceStatus",
        ),
    ]
