# Generated by Django 5.0.1 on 2024-02-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_rename_servicemodel_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicehistory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicehistory",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicestatus",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicestatus",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
