# Generated by Django 5.0.1 on 2024-03-05 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0016_service_deleted_at_service_restored_at_and_more"),
        ("vehicles", "0022_alter_vehicle_brand_alter_vehicle_owner"),
        ("workshops", "0046_alter_review_body"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="vehicle",
            field=models.ForeignKey(
                help_text="Vehicle",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="services",
                to="vehicles.vehicle",
                verbose_name="vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="workshop",
            field=models.ForeignKey(
                help_text="Workshop",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="services",
                to="workshops.workshop",
                verbose_name="workshop",
            ),
        ),
        migrations.AlterField(
            model_name="servicehistory",
            name="responsable",
            field=models.ForeignKey(
                help_text="Responsable",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="service_histories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="responsable",
            ),
        ),
    ]
