from django.urls import path

from . import views

app_name = "workshops"

urlpatterns = (
    path(
        "",
        views.WorkshopListView.as_view(),
        name="list",
    ),
    path(
        "/new",
        views.WorkshopListNewView.as_view(),
        name="new",
    ),
    path(
        "/trending",
        views.WorkshopListTrendingView.as_view(),
        name="trending",
    ),
    path(
        "/recommended",
        views.WorkshopListRecommendedView.as_view(),
        name="for-you",
    ),
    path(
        "/<int:workshop_id>",
        views.WorkshopDetailView.as_view(),
        name="detail",
    ),
    path(
        "/<int:workshop_id>/banner",
        views.WorkshopBannerView.as_view(),
        name="banner",
    ),
    path(
        "/<int:workshop_id>/brands",
        views.WorkshopBrandListView.as_view(),
        name="brands",
    ),
    path(
        "/<int:workshop_id>/image",
        views.WorkshopImageView.as_view(),
        name="image",
    ),
    path(
        "/<int:workshop_id>/contacts",
        views.WorkshopContactListView.as_view(),
        name="contacts",
    ),
    path(
        "/<int:workshop_id>/employees",
        views.WorkshopEmployeeListView.as_view(),
        name="employees",
    ),
    path(
        "/<int:workshop_id>/services",
        views.WorkshopServiceView.as_view(),
        name="services",
    ),
    path(
        "/<int:workshop_id>/specialities",
        views.WorkshopSpecialityView.as_view(),
        name="specialities",
    ),
    path(
        "/<int:workshop_id>/vehicles",
        views.WorkshopVehicleView.as_view(),
        name="vehicles",
    ),
    path(
        "/<int:workshop_id>/questions",
        views.QuestionListView.as_view(),
        name="questions",
    ),
    path(
        "/<int:workshop_id>/reviews",
        views.ReviewListView.as_view(),
        name="reviews",
    ),
    path(
        "/<int:workshop_id>/questions/<int:question_number>",
        views.QuestionDetailView.as_view(),
        name="question-detail",
    ),
    path(
        "/<int:workshop_id>/questions/<int:question_number>/responses",
        views.QuestionResponseListView.as_view(),
        name="question-responses",
    ),
    path(
        "/<int:workshop_id>/reviews/<int:review_number>",
        views.ReviewDetailView.as_view(),
        name="review-detail",
    ),
    path(
        "/<int:workshop_id>/reviews/<int:review_number>/images",
        views.ReviewPhotoView.as_view(),
        name="review-images",
    ),
    path(
        "/<int:workshop_id>/reviews/<int:review_number>/response",
        views.ReviewResponseView.as_view(),
        name="review-response",
    ),
    path(
        "/specialities",
        views.SpecialityListView.as_view(),
        name="speciality-list",
    ),
)
