# Generated by Django 4.2.7 on 2024-01-25 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reviews.models.review_photo_model


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0008_alter_servicemodel_workshop"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workshops", "0008_remove_reviewphotomodel_review_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Review id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "review",
                    models.TextField(
                        help_text="Review message",
                        max_length=255,
                        verbose_name="review",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1,
                        default=4.5,
                        help_text="Score",
                        max_digits=2,
                        verbose_name="score",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Responded at",
                        verbose_name="responded at",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Client",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Service",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="services.servicemodel",
                        verbose_name="service",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Workshop",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="workshops.workshopmodel",
                        verbose_name="workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "review",
                "verbose_name_plural": "reviews",
                "db_table": "review",
            },
        ),
        migrations.CreateModel(
            name="ReviewResponseModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Question id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        help_text="reviewed at", max_length=255, verbose_name="response"
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Responded at",
                        verbose_name="responded at",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Client who asked the question",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        help_text="Review",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="reviews.reviewmodel",
                        verbose_name="review",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Workshop who the question was asked",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_responses",
                        to="workshops.workshopmodel",
                        verbose_name="workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "review response",
                "verbose_name_plural": "review responses",
                "db_table": "review_response",
            },
        ),
        migrations.CreateModel(
            name="ReviewPhotoModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Vehicle brand id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Photo",
                        upload_to=reviews.models.review_photo_model.rename,
                        verbose_name="photo",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        help_text="Review",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="reviews.reviewmodel",
                        verbose_name="review",
                    ),
                ),
            ],
            options={
                "verbose_name": "review photo",
                "verbose_name_plural": "review photos",
                "db_table": "review_photo",
            },
        ),
    ]
