# Generated by Django 5.0.1 on 2024-03-07 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_rename_client_review_user"),
        ("workshops", "0051_alter_speciality_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                editable=False,
                help_text="User",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="workshop",
            field=models.ForeignKey(
                editable=False,
                help_text="Workshop",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="workshops.workshop",
                verbose_name="workshop",
            ),
        ),
    ]
