# Generated by Django 5.0 on 2023-12-13 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationModel',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Autogenerated (non editable) email verification id', primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('code', models.CharField(help_text='User email verification code', max_length=4, verbose_name='code')),
                ('is_valid', models.BooleanField(default=True, help_text='User email verification validity status', verbose_name='is valid')),
                ('date_requested', models.DateTimeField(auto_now_add=True, help_text='User email verification request timestamp', verbose_name='date requested')),
                ('expiration_date', models.DateTimeField(help_text='User email verification expiration timestamp', verbose_name='expiration at')),
                ('user', models.OneToOneField(help_text='User user', on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'email verification',
                'verbose_name_plural': 'email verifications',
                'db_table': 'email_verification',
            },
        ),
    ]
