# Generated by Django 5.0 on 2023-12-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_remove_emailverificationmodel_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationmodel',
            name='code',
            field=models.CharField(help_text='User hashed email verification code', max_length=128, verbose_name='code'),
        ),
    ]
