# Generated by Django 5.0 on 2023-12-15 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_emailverificationmodel_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCodeTypeModel',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Autogenerated (non editable) verification code type id', primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('code', models.CharField(help_text='Verification code type code', max_length=5, unique=True, verbose_name='code')),
                ('name', models.CharField(help_text='Verification code type name', max_length=128, unique=True, verbose_name='name')),
                ('description', models.TextField(help_text='Verification code type description', max_length=512, verbose_name='description')),
            ],
            options={
                'verbose_name': 'code type',
                'verbose_name_plural': 'code types',
                'db_table': 'code_type',
            },
        ),
        migrations.CreateModel(
            name='VerificationCodeModel',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Autogenerated (non editable) verification code id', primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('code', models.CharField(help_text='User hashed verification code', max_length=128, verbose_name='code')),
                ('date_requested', models.DateTimeField(auto_now_add=True, help_text='User verification code request timestamp', verbose_name='date requested')),
                ('user', models.OneToOneField(help_text='User user', on_delete=django.db.models.deletion.PROTECT, related_name='code_verification', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('type', models.ForeignKey(help_text='User verification code type', on_delete=django.db.models.deletion.PROTECT, related_name='code_verification', to='security.verificationcodetypemodel', verbose_name='type')),
            ],
            options={
                'verbose_name': 'code verification',
                'verbose_name_plural': 'code verifications',
                'db_table': 'code_verification',
            },
        ),
        migrations.DeleteModel(
            name='EmailVerificationModel',
        ),
    ]
