# Generated by Django 5.0 on 2023-12-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_verificationcodetypemodel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationcodetypemodel',
            options={'verbose_name': 'verification code type', 'verbose_name_plural': 'verification code types'},
        ),
        migrations.AlterModelTable(
            name='verificationcodetypemodel',
            table='verification_code_type',
        ),
    ]
