# Generated by Django 5.0 on 2023-12-15 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_alter_verificationcodemodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodemodel',
            name='code',
            field=models.CharField(editable=False, help_text='User hashed verification code', max_length=128, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='verificationcodemodel',
            name='type',
            field=models.ForeignKey(editable=False, help_text='User verification code type', on_delete=django.db.models.deletion.PROTECT, related_name='verification_code', to='security.verificationcodetypemodel', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='verificationcodemodel',
            name='user',
            field=models.OneToOneField(editable=False, help_text='User user', on_delete=django.db.models.deletion.PROTECT, related_name='verification_code', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
