# Generated by Django 4.2.7 on 2024-01-17 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("security", "0008_alter_verificationcodemodel_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcodemodel",
            name="user",
            field=models.OneToOneField(
                editable=False,
                help_text="User user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_code",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
