# Generated by Django 5.0.1 on 2024-02-22 23:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0009_alter_verificationcodemodel_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VerificationCodeModel",
            new_name="VerificationCode",
        ),
        migrations.RenameModel(
            old_name="VerificationCodeTypeModel",
            new_name="VerificationCodeType",
        ),
    ]
