# Generated by Django 5.0.1 on 2024-02-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0010_rename_verificationcodemodel_verificationcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationcode",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verificationcodetype",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verificationcodetype",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
