# Generated by Django 4.2.7 on 2023-12-09 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vehicles.models.vehicle_model


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleBrandModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Vehicle brand id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Vehicle brand",
                        max_length=50,
                        unique=True,
                        verbose_name="vehicle brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle brand",
                "verbose_name_plural": "vehicle brands",
                "db_table": "vehicle_brand",
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Service id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Model", max_length=50, verbose_name="model"
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Year", verbose_name="year"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        help_text="Nickname",
                        max_length=50,
                        null=True,
                        verbose_name="nickname",
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        help_text="VIN", max_length=17, verbose_name="vin"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo",
                        null=True,
                        upload_to=vehicles.models.vehicle_model.rename,
                        verbose_name="photo",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        help_text="Brand",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="vehicles.vehiclebrandmodel",
                        verbose_name="brand",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Workshop",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle",
                "verbose_name_plural": "vehicles",
                "db_table": "vehicle",
            },
        ),
    ]
