# Generated by Django 4.2.7 on 2024-01-15 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
    ]
