# Generated by Django 4.2.7 on 2024-01-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0003_vehiclemodel_plate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="nickname",
            field=models.CharField(
                default="Juan",
                help_text="Nickname",
                max_length=50,
                verbose_name="nickname",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="plate",
            field=models.CharField(
                blank=True,
                help_text="Plate",
                max_length=7,
                null=True,
                verbose_name="plate",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="vin",
            field=models.CharField(
                blank=True,
                help_text="VIN",
                max_length=17,
                null=True,
                verbose_name="vin",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Year", null=True, verbose_name="year"
            ),
        ),
    ]
