# Generated by Django 4.2.7 on 2024-01-25 09:45

from django.db import migrations, models
import vehicles.models.vehicle


class Migration(migrations.Migration):
    dependencies = [
        (
            "vehicles",
            "0004_alter_vehiclemodel_nickname_alter_vehiclemodel_plate_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiclemodel",
            name="photo",
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image",
                null=True,
                upload_to=vehicles.models.vehicle.rename,
                verbose_name="image",
            ),
        ),
    ]
