# Generated by Django 5.0.1 on 2024-02-02 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0007_alter_vehiclemodel_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="plate",
            field=models.CharField(
                blank=True,
                help_text="Plate",
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Plate must be in the format 'A000000'.",
                        regex="^(E|e)?[a-zA-Z]\\d{6}$",
                    )
                ],
                verbose_name="plate",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="vin",
            field=models.CharField(
                blank=True,
                help_text="VIN",
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="VIN must be 17 characters long.",
                        regex="^[A-HJ-NPR-Z0-9]{17}$",
                    )
                ],
                verbose_name="vin",
            ),
        ),
    ]
