# Generated by Django 5.0.1 on 2024-02-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0008_alter_vehiclemodel_plate_alter_vehiclemodel_vin"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclemodel",
            name="archived",
            field=models.BooleanField(
                default=False, help_text="Archived", verbose_name="archived"
            ),
        ),
    ]
