# Generated by Django 5.0.1 on 2024-02-05 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0010_alter_vehiclemodel_plate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehiclemodel",
            old_name="archived",
            new_name="is_archived",
        ),
    ]
