# Generated by Django 5.0.1 on 2024-02-12 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0011_rename_archived_vehiclemodel_is_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="plate",
            field=models.CharField(
                blank=True,
                help_text="Plate",
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Plate must be in the format 'A000000'.",
                        regex="^(A{1,2}|B|C|D{1,2}|F|G|L|H|I|T|P{1,2}|U|J|R|S|M|O[EFMPI]|E[AGLMEIDX]|VC|WD|YX|N?Z|K)\\d{6}$",
                    )
                ],
                verbose_name="plate",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="vin",
            field=models.CharField(
                blank=True,
                help_text="VIN",
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="VIN must be 17 characters long.",
                        regex="^[A-HJ-NPR-Z\\\\d]{8}[\\\\dX][A-HJ-NPR-Z\\\\d]{2}\\\\d{6}$",
                    )
                ],
                verbose_name="vin",
            ),
        ),
    ]
