# Generated by Django 5.0.1 on 2024-02-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0015_rename_is_active_vehiclemodel_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Deleted", verbose_name="is deleted"
            ),
        ),
    ]
