# Generated by Django 5.0.1 on 2024-02-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0018_rename_vehiclemodel_vehicle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehiclebrand",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehiclebrand",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
