# Generated by Django 5.0.1 on 2024-02-23 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0020_remove_vehicle_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="plate",
            field=models.CharField(
                blank=True,
                help_text="Plate",
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Plate must be in the format 'A000000'.",
                        regex="^((A{1,2}|B|C|D{1,2}|F|G|L|H|I|T|P{1,2}|U|J|R|S|M|O[EFMPI]|E[AGLMEIDX]|VC|WD|YX|N?Z)\\d{6})|(K\\d{7})$",
                    )
                ],
                verbose_name="plate",
            ),
        ),
    ]
