# Generated by Django 5.0.1 on 2024-03-05 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0021_alter_vehicle_plate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.ForeignKey(
                help_text="Brand",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="vehicles",
                to="vehicles.vehiclebrand",
                verbose_name="brand",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="vehicles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
    ]
