# Generated by Django 5.0.1 on 2024-03-05 14:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0023_alter_vehicle_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vehicle",
            unique_together={
                ("nickname", "owner", "deleted_at"),
                ("plate", "owner", "deleted_at"),
                ("vin", "owner", "deleted_at"),
            },
        ),
    ]
