# Generated by Django 5.0.1 on 2024-03-06 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0025_vehicle_created_at_vehicle_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                help_text="Owner",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="vehicles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
    ]
