name: Code checks
on:
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cache dependencies
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.11.6'
          cache: 'pip'
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.dev.txt
      - name: Lint
        run: flake8
  run-unit-tests:
    name: Run unit tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cache dependencies
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.11.6'
          cache: 'pip'
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt
      - name: Run unit tests
        run: python manage.py test
