name: Release Docker image

on:
  push:
    tags:
      - v**

jobs:
  docker:
    name: Build, test and push Docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ github.ref_name }}
            ${{ env.DOCKER_REPO }}:latest

  release:
    name: Create GitHub release
    needs: docker
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create GitHub release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha')  || contains(github.ref, 'preview') }}
